spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/courses_app
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: validate
  liquibase.change-log: classpath:db/changelog/db.changelog.yaml
